name: ClaimChunkMongoDB
version: '${project.version}'
main: de.glowman554.claimchunkmongodb.ClaimChunkMongoDB
api-version: '1.20'
depend:
  - ClaimChunk
commands:
  cache:
    permission: claimchunkmongodb.cache